### PR TITLE
Update dislocker_man

### PR DESCRIPTION
**Pull request by greenlion**
Update disklocker_man, fix typo in command name for 'file' mode (it should be dislocker-file, not dislocker).

### CODE REVIEW

**Comment by Aorimn** [comment]
It really depends on the way dislocker is compiled. Please, have a look at the develop branch and the new man pages.

**Comment by greenlion** [comment]
Ok.  It just confused me because I followed directions in README.md, and then used the man page, but man page said to use dislocker, but I needed to use disklocker-file (no BEK file).  I guess you can ignore this pull request then, but I think it would still be useful for people who use master (the default, so I assume most people).

Great tool btw, got me out of a bind.

**Comment by Aorimn** [comment]
The BEK file is the file BitLocker is putting on the USB key as a recovery method.

Whether you should use dislocker or dislocker-file is independant from the access method, both will work with the BEK file or not.

**Comment by greenlion** [comment]
Hi,

sudo dislocker -V /dev/sda2
-p146817-445665-192258-473561-381106-696168-146839-394339 -- decryped.ntfs
[sudo] password for justin:
fuse: bad mount point `decryped.ntfs': No such file or directory

Same commandline arguments with dislocker-file works fine:
sudo dislocker-file -V /dev/sda2
-p146817-445665-192258-473561-381106-696168-146839-394339 -- decryped.ntfs
(no output because it is running)


What am I doing wrong with the first command?  That is verbatim from
dislocker(1) and why I changed the man page.

--Justin

**Comment by Aorimn** [comment]
You have to look at the "fuse mode" section of the manual for the first section. The last parameter thus shouldn't be decrypted.ntfs but an existing folder.

**Pull request closed without merging**
