### PR TITLE
add ability to read password from the environment

### PR DESCRIPTION
**Pull request by mhogomchungu**

### CODE REVIEW

**Comment by Aorimn** [comment]
Good idea, thanks!

**Comment by Nable80** [comment]
I hope you are aware that other processes with the same UID can read environment variables of a running process (see ``/proc/$PID/environ`` on Linux, there should be similar thing in other systems). That's why passing passwords via command line arguments and environment variables is usually avoided. There should be some disclaimer about the presence of this feature.

One can try to improve the situation by doing ``memset(env_pass, 0, (size_t)nb_read);`` after ``memcpy`` but it's only a partial solution.

Btw, is this ``'\n'`` really needed? Function ``chomp`` seems to be safe for strings without line endings.
This way one can use simple ``strdup`` instead of multiple lines of code.

**Comment by mhogomchungu** [comment]
I couldn't figure out what "chomp" function is doing and decided to produce the same output getline() would produce so that the function could see the same input from both code paths.

I didn't know about the environment variable thing and somebody suggested doing it this way.

dislocker-fuse requires root's privileges to run and any tool that will pass it a password through the environment would have to be running privileged and the password should be safe from normal users.

A better alternative is to allow dislocker to read passwords from pipes like i suggested in this[1] bug report.

[1]https://github.com/Aorimn/dislocker/issues/169

**Comment by Nable80** [comment]
Oops, I've missed the root requirement (usually FUSE is available for regular users, permissions for reading/writing specific partitions can also be configured using udev rules). OK.

**Comment by Rondom** [comment]
Why would dislocker need root? Last time I tried (provided the correct permissions), it did not.

**Comment by mhogomchungu** [comment]
@Rondom 

Without root's privileged, you unlocked a bitlocker volume and then mount the file system on the volume?

1. What permissions is disclocker installed with?
2. What commands did you use to accomplish the above two steps?

As far as i know, access to block devices requires root's privileges and mount command also requires root's privileges

[ink@mtz ~]$ dislocker-fuse -v -v -v -v  /dev/loop0  -u  -- -oallow_root /home/ink/aaa                                 
Mon Jul  8 08:05:29 2019 [DEBUG] Verbosity level to DEBUG (4) into 'stdout'
Mon Jul  8 08:05:29 2019 [INFO] dislocker by Romain Coltel, v0.7.1 (compiled for Linux/x86_64)
Mon Jul  8 08:05:29 2019 [INFO] Compiled version: master:865d1d3
Mon Jul  8 08:05:29 2019 [DEBUG] --- Config...
Mon Jul  8 08:05:29 2019 [DEBUG]    Verbosity: 4
Mon Jul  8 08:05:29 2019 [DEBUG]    Trying to decrypt '/dev/loop0'
Mon Jul  8 08:05:29 2019 [DEBUG]        using the user's password method
Mon Jul  8 08:05:29 2019 [DEBUG]                -> '(null)'
Mon Jul  8 08:05:29 2019 [DEBUG]    Using the first valid metadata block
Mon Jul  8 08:05:29 2019 [DEBUG] ... End config ---
Mon Jul  8 08:05:29 2019 [DEBUG] Trying to open '/dev/loop0'...
Mon Jul  8 08:05:29 2019 [DEBUG] Trying to open '/dev/loop0'...
Mon Jul  8 08:05:29 2019 [ERROR] Failed to open file '/dev/loop0': Permission denied
Mon Jul  8 08:05:29 2019 [DEBUG] Trying to open '/dev/loop0'...
Mon Jul  8 08:05:29 2019 [ERROR] Failed to open file '/dev/loop0': Permission denied
Mon Jul  8 08:05:29 2019 [CRITICAL] Failed to open /dev/loop0: Permission denied
Mon Jul  8 08:05:29 2019 [DEBUG] Freeing pointer at address 0x55d5be0ce960
Mon Jul  8 08:05:29 2019 [DEBUG] Trying to close fd #0...
[ink@mtz ~]$

**Comment by Nable80** [comment]
> As far as i know, access to block devices requires root's privileges and mount command also requires root's privileges

One doesn't need root to use FUSE (read-write access to /dev/fuse is enough, it's usually achieved via membership in ``fuse`` group) and it's possible to allow specific users access some specific block devices using proper udev rules.

Btw, default setup (even without special udev rules) in some distros also allows members of group 'disk' to access disks:
```# ls -l /dev/loop0 /dev/sda
brw-rw---- 1 root disk 7, 0 May 28 14:20 /dev/loop0
brw-rw---- 1 root disk 8, 0 Jun 30 06:12 /dev/sda```
I **won't** recommend adding regular user to this group (it would lead to access to ALL of the disks) but udev rules for something fine-grained are OK.

**Pull request merged**
